### ISSUE TITLE
empty overlaps.txt

### ISSUE THREAD

**Issue by AnjaliC4** [UcarLab/AMULET#6]
Hello,
Thanks for this really nice tool!! I have two questions:

1. I am facing some issues in the implementation: As a first pass, I am trying to compare the doublet rate identified in mouse+human mixed species barnyard experiment. The data is generated with default 10x pipeline. For mixed species, it generates the following first few columns in singlecell.csv. The default is_cell_barcode is 9, here that corresponds to is_GRCh38_cell_barcode. 
barcode,total,duplicate,chimeric,unmapped,lowmapq,mitochondrial,nonprimary,passed_filters,is_GRCh38_cell_barcode,is_mm10_cell_barcode
The pipeline returns empty overlap.txt. Any clues why? 

2. Also, if I were to use some other pipeline than 10x that does not produce singlecell.csv. I essentially need a "comma" separated csv file that has barcode info (--bcidx) and one column indicating whether it is a cell barcode or not (specified in --iscellidx) ? How do I specify --cellidx (not sure what that corresponds to)

**Comment by alperoglu** [comment]
Hi Anjali,

Glad to hear that you're using ATAC-DoubletDetector. 

Unfortunately we haven't yet tested the method with mixed species and that singlecell.csv file format you sent. The overlaps file can be empty if it can't find any of the cell barcodes in the bam file. How many rows do you have in column 9(is_GRCh38_cell_barcode) that has the value 1? Can you also try setting the _--iscellidx_ option to 10 instead of 9 and see what happens?

For you second question, yes you can use a 2-column CSV file that has the barcodes (_--bcidx_) and whether that barcode is a cell or not (_--iscellidx_)(values are 0 or 1). The  _--cellidx_ is for older versions of **cellranger-atac count** outputs, where there is also a column in the singlecell.csv that contains a cell id for the barcode in "cell_#" format. We also wanted to provide the multiplet cells with that cell id in addition to the barcodes. That column is not included in the new version of cellranger-atac singlecell.csv file and you can specify the same column as _--bcidx_ for that option. Both _--bcidx_ and _--cellidx_ are directed to the first column in your CVS file in default. 

Best,
Alper

**Comment by AnjaliC4** [comment]
Hi Alper,

I can confirm that setting --iscellidex to 10 gives the same error. (my first q)

Traceback (most recent call last):
  File "/home/anjali5/atac-doublet-detector/ATAC-DoubletDetector_Release_5-17-2021/ATACDoubletDetector.py", line 190, in <module>
    lengths = filtereddata[:,2]-filtereddata[:,1]+1
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Since it could be quite useful to compare ATAC-doublet-detector's results to a mixed-species analysis result, I would really appreciate it if you could help me sort this error.

Thanks so much,
Anjali

**Comment by AnjaliC4** [comment]
As an update, I created another column in singlecell.csv for is_cell_id with 1 for is_GRCh38_cell_barcode=1 and is_mm10_cell_barcode=1 or when both are 1 (rest 0), and specified the right column number in  --iscellidex. I still get the error mentioned above. The overlapSummary.txt has data:
Cell Id Number of Valid Read Pairs	Number of Overlaps	Barcode Total Number of Reads
AAACGAAAGATCCGAG-1	0	0	AAACGAAAGATCCGAG-1	18517
AAACGAAAGCGTGTTT-1	0	0	AAACGAAAGCGTGTTT-1	8001
AAACGAAAGGCAAGCT-1	0	0	AAACGAAAGGCAAGCT-1	36236
AAACGAAAGTCGAAAT-1	0	0	AAACGAAAGTCGAAAT-1	36148
AAACGAAAGTGATTAG-1	0	0	AAACGAAAGTGATTAG-1	11194
AAACGAAAGTGCTAGG-1	0	0	AAACGAAAGTGCTAGG-1	15326
AAACGAACAAGCTTTG-1	0	0	AAACGAACAAGCTTTG-1	38497

However, the overlap.txt has only headers and is empty which is why the next step of doublet detection is failing. Any help would be greatly appreciated.

Thanks
Anjali

**Comment by ajt986** [comment]
Sorry for the late response Anjali. It looks like all the reads are being filtered out since the number of valid read pairs is 0 for each of these. The program is indeed seeing the reads for each cell as indicated by the total number of reads so there is something causing them to be filtered from further processing. I can see a few possible reasons for this:

1) The reads are not meeting the flags used in the program.  More information can be found in StatSummary.txt, which will indicate if reads are excluded due to low mapping quality or duplicate flags.

2) If the above is not the case then the reads are being filtered out due to insert size (by default the insert size should be between 0 and 900bp (~6 nucleosomes)) or filtered because of the following flags:

NOT ReadPairedFlag 
ReadUnmappedFlag
MateUnmappedFlag
isSecondaryOrSupplementary
getDuplicateReadFlag

Hopefully this simply a mapping quality problem, where you can just set a lower threshold using --mapqthresh (default is 30). 

Best,
Asa

**Comment by AnjaliC4** [comment]
Hi Asa,

Thanks for your response. It is really strange because - this is how the Statsummary looked. 
Total Reads:    712742582
Duplicate Reads:        188786010
Low Mapping Quality Reads (<=30):	84645073
Valid Reads:    0
Total Reads:    712742582
Mean Read Length:	NaN
Mean Insert Size:	NaN

I have also attached the a screenshot from 10x pipleine data quality. You will see that 89% reads are passing mapq>30.
Thank you very much for helping me sort this out. 

<img width="1163" alt="Screen Shot 2021-06-15 at 3 04 00 PM" src="https://user-images.githubusercontent.com/60046859/122109129-03d17780-cdeb-11eb-9a7a-b28e4daf71d5.png">


Anjali

**Comment by ajt986** [comment]
Looking into it further, since the total number of reads per cell/nucleus are being reported, the error is coming from:

if(!isnegative && u.isValidRead(next) && insertsize > 0 && next.getMappingQuality() > _mapqthreshold) 

We can rule out mapping quality based on the summary you provided.  This leaves:

**!isnegative** : Which is just checking to make sure we are using the forward strand read using the ReadNegativeStrandFlag

**insertsize > 0**: Which is calculated using getInferredInsertSize() in the samtools HTSJDK library

**u.isValidRead(next)**: Which is a function that checks to see if any of these flags are true for exclusion:
_NOT ReadPairedFlag_
_ReadUnmappedFlag_
_MateUnmappedFlag_
_isSecondaryOrSupplementary_
_<s>DuplicateReadFlag</s>_ - Note: We know this one is being passed from the duplicate read count in the statistics
and _whether the read's reference index matches the mate's reference index_

One of these checks is not being passed. Best I can do on my end for now is work on pushing an update that will give a better summary of how many reads are not passing these specific checks/flags.
